### ISSUE TITLE
nonono

### ISSUE THREAD

**Issue by zhangyu1818** [zilingziling/zilingziling.github.io#2]

**Comment by 723156735** [comment]
:couplekiss:

**Comment by 723156735** [comment]
:heart:

**Comment by 723156735** [comment]
:rabbit:

**Comment by 723156735** [comment]
:ok_woman: :kissing_heart: :rabbit: :cupid:

**Comment by 723156735** [comment]
❤️❤️❤️❤️❤️❤️❤️❤️

**Comment by 723156735** [comment]
:clock5: :clock2: :clock12:

**Comment by 723156735** [comment]
:five::two::zero::repeat_one:

**Comment by 723156735** [comment]
```
while ( life ){
    love++;
}
```

**Comment by 723156735** [comment]
99669999996669999996699666699666999966699666699
99699999999699999999699666699669966996699666699
99669999999999999996699666699699666699699666699
99666699999999999966666999966699666699699666699
99666666999999996666666699666699666699699666699
99666666669999666666666699666669966996699666699
99666666666996666666666699666666999966669999996

**Comment by 723156735** [comment]
[ 73, 32, 76, 79, 86, 69, 32, 85 ]

**Comment by zilingziling** [comment]
> [ 73, 32, 76, 79, 86, 69, 32, 85 ]

数组是什么意思

**Comment by 723156735** [comment]
const str = 👩‍❤️‍👩;
for(let i = 0;i<str.length;i++){
    console.log(str[i])
}

**Comment by zilingziling** [comment]
> const str = 👩‍❤️‍👩;
> for(let i = 0;i<str.length;i++){
> console.log(str[i])
> }
got it

# # @

**Comment by 723156735** [comment]
http://miloyip.com/misc/sv2019.html?SGFwcHkgVmFsZW50aW5lJ3MgRGF5
